/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package POO1YN;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author yosue
 */
public class frameVehiculos extends javax.swing.JFrame {
    
    ArrayList<Vehiculo> vehiculos = new ArrayList<>(); // ArrayList para las clases que se creen
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameVehiculos.class.getName());

    /**
     * Creates new form frameVehiculos
     */
    public frameVehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfColor = new javax.swing.JTextField();
        tfMarca = new javax.swing.JTextField();
        cbAdicional = new javax.swing.JComboBox<>();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbAdicional = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbAdicional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Diésel", "Eléctrico", "Híbrido" }));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coche", "Moto" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registro de vehículos");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Color:");

        lbAdicional.setText("Combustible:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        taInfo.setColumns(20);
        taInfo.setRows(5);
        jScrollPane1.setViewportView(taInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrar)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lbAdicional))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMarca)
                            .addComponent(tfColor)
                            .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbAdicional, 0, 90, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAdicional)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
        //Recoger la selección
        String seleccion = cbTipo.getSelectedItem().toString();
        // Modelos segun el tipo de clase
        DefaultComboBoxModel<String> modeloCombustible = new DefaultComboBoxModel<>(
            new String[]{"Gasolina", "Diésel", "Eléctrico", "Híbrido"});
        DefaultComboBoxModel<String> modeloCilindrada = new DefaultComboBoxModel<>(
            new String[]{"50cc", "125cc", "250cc", "300cc"});
        
        switch (seleccion) {
            // Si es coche cambia el label y el combobox a combustible
            case "Coche":
                lbAdicional.setText("Combustible:");
                cbAdicional.setModel(modeloCombustible);
                break;
            // Si es moto cambia el label y el combobox a cilindrada
            case "Moto":
                lbAdicional.setText("Cilindrada:");
                cbAdicional.setModel(modeloCilindrada);
                break;
        }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        taInfo.setText(""); // Vaciar TextArea
        
        // Recoger las entradas
        String tipoVehiculo = cbTipo.getSelectedItem().toString();
        String marca = tfMarca.getText();
        String color = tfColor.getText();
        String cmpAdicional = cbAdicional.getSelectedItem().toString();
        
        // Validar que no hayan campos vacíos
        if (marca.isBlank() || color.isBlank()) {
            // Mostrar diálogo para advertir al usuario
            javax.swing.JOptionPane.showMessageDialog(
                    this,                                     
                    "Rellena todos los campos para registrar un vehículo.", 
                    "Error",                       
                    javax.swing.JOptionPane.WARNING_MESSAGE   
                );
        } else {
            // Si se ha introducido un coche
            if (tipoVehiculo.equals("Coche")) {
                // Crear coche, añadirlo al ArrayList y mostrar información en TextArea
                Coche nuevoCoche = new Coche(marca, color, cmpAdicional);
                String infoCoche = nuevoCoche.mostrarInfo();
                vehiculos.add(nuevoCoche);
                taInfo.setText(infoCoche);
            }
            // Si se ha introducido una moto
            if (tipoVehiculo.equals("Moto")) {
                // Crear moto, añadirla al ArrayList y mostrar información en TextArea
                Moto nuevaMoto = new Moto(marca, color, cmpAdicional);
                String infoMoto = nuevaMoto.mostrarInfo();
                vehiculos.add(nuevaMoto);
                taInfo.setText(infoMoto);
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameVehiculos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbAdicional;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAdicional;
    private javax.swing.JTextArea taInfo;
    private javax.swing.JTextField tfColor;
    private javax.swing.JTextField tfMarca;
    // End of variables declaration//GEN-END:variables
}
